// {
//         ID: "12",
//         title: "Google Books Finder",
//         slug: "google-books-finder",
//         story: "One day, while frantically working through an online Java Scripts course, I made the decision to take the author's advice and create an application that can retrieve any data from any public API. You know, I was just starting out in the IT field, and I thought the assignment was both challenging and not overly complicated. I've wandered through the list of accessible APIs and have chosen to begin with Google Books. That is how one of my most fascinating adventures begun. The app is not as logical and coherent as it could be because I experimented a lot of different programming techniques there.  It was quite little and simple at first, but it ended up being rather sophisticated. New features has appeared one after another. In the end, there is an app that searches for books based on specified parameters, sorts and filters the results, removes books from both the retrieve and display results, generates a local temporary storage, and much more. So - if you enjoy reading books, have a fun ;) ",
//         description: "Finds books in Google Books resources and performs multiple actions with the found data.",
//         longDescription: [
//             "The Google Books resource browser application. Books can be selected based on the name, author, and label.",
//             "Results can be sorted and filtered according to the author, language, title, subtitle, labels, and year of publication.",
//             "It allows local favourites to be created, provides shop access and provides book details.",
//             "It is paginated, and neatly styled with material-ui",
//             "My approach involves applying a recursive continuous fetching thunk, which takes longer than a single step fetch because the admin restricts the number of book records that can be fetched in a single fetch and I don't know how many entries are actually available.",
//         ],
//         live: "https://kiszuriwalilibori.github.io/books/",
//         github: "https://github.com/Kiszuriwalilibori/books",
//         features: ["react", "typescript", "redux", "axios", "react-query", "formik", "saga", "jest", "web workers"],
//         category: "A",
//         slides: ["/images/project_images/gbfinder2.jpg", "/images/project_images/gbfinder3.jpg"],
//     },
